### ISSUE TITLE
Outlier clamp range selection

### ISSUE THREAD

**Issue by Yang2888** [rsinghlab/AltumAge#10]
Hi, I see that when preprocessing the dataset, there is a function "remove_outliers", which is used to delete cpg datapoints who are outside of range [-0.5, 1]. May I ask how is this range selected? It seems that this is not mentioned in the paper

**Comment by lucascamillomd** [comment]
Hi! The code for the python script my_functions on the Google Drive under the folder Others. It was just some basic QC to remove samples which have clearly wrong methylation values

**Comment by Yang2888** [comment]
Oh I know it is in the my_functions.py, the question I have is why the range is [-0.5, 1] instead of other range like [-1,1] or [-1, 0.5]? Like is there some paper talking about the definition of "outlier" in methylation dataset? Or this is actually some hyperparameter that can be changed?

**Comment by lucascamillomd** [comment]
Methylation values are bounded by 0 to 1, but sometimes normalization techniques change this range slightly, which is why it is setup as -0.5 to 1

**Comment by Yang2888** [comment]
Oh I see, thank you for the clarification!
