### ISSUE TITLE
How do you handle missing CpGs?

### ISSUE THREAD

**Issue by JuBauer** [rsinghlab/AltumAge#4]
Hello,
I am trying to use your work on a data set but I end up with a few missing CpGs after processing (or even without processing, there are 5 CpGs missing in my data set out of the 20318 you use in your model). Is there an imputing method you would recommend or a way of telling the model to ignore missing data?

**Comment by lucascamillomd** [comment]
Hello, I'm so sorry about the delay. I would recommend using 0 as the scaled value for the missing CpGs, as that will likely have the least effect on the final prediction of the model given that is the median of the data used to train AltumAge. Nevertheless, given how many CpGs are used to train the neural network (>20k), it's unlikely that any five will make a substantial difference for the predicted age. Hope that helps!
