### ISSUE TITLE
The function `transform_age` is missing

### ISSUE THREAD

**Issue by Kaushalya** [rsinghlab/AltumAge#6]
Hi,

Thanks for sharing this codebase. However, the module `my_functions` could not be found in this repo. Could you please add it?

**Comment by lucascamillomd** [comment]
Dear Kaushalya, 

I just added the python code my_functions to the Google Drive under the folder Others. Essentially, it is a log-linear transformation as seen in Horvath's 2013 paper with adult age set to 20. 

Best,
Lucas
