### ISSUE TITLE
BMIQcalibration

### ISSUE THREAD

**Issue by kmkappa** [rsinghlab/AltumAge#7]
hi!
great work, cheers !

You recommend using BMIQCalibration-normalized methylation data. to do this we need to use _BMIQcalibration()_ function which requires as SummarizedExperiment a clean beta-matrix created with _clean-beta()_ function. This function reduces a beta-matrix to the 18747 CpGs used to calibrate methylation profiles in MEAT2.0. so obtained beta-matrix must miss some (at least 1571 probes) of 20318 CpG sites listed the file "CpGsites.csv". is that correct ? or am I missing something ?

Thank you!

**Comment by lucascamillomd** [comment]
Hi! I was wondering if you used BMIQCalibration from Horvath's 2013 R script or if you used this function from another package. The 20318 CpG sites should in theory be common to Illumina's 27k, 450k, and EPICv1 arrays. In any case, if those 1571 probes are still being filtered out, I would either not use BMIQCalibration (which is not a huge deal) or just add those probes with a value 0 after scaling.

**Comment by kmkappa** [comment]
Hi!
thank you for your response.
I used _BMIQcalibration()_ function from "MEAT: Muscle Epigenetic Age Test" R package. I don't think it's the same you are referring to. In this case I will skip the BMIQCalibration as you suggest.

thank you and all the best!
