### ISSUE TITLE
Could you please release the train/valid/test split data IDs for methylation_data.pkl?

### ISSUE THREAD

**Issue by ZwormZ** [rsinghlab/AltumAge#8]
Hi, I'd like to thank you for your excellent work！I am currently working on a project related to your research, and I find your dataset methylation_data.pkl extremely helpful.

To better understand and utilize this dataset, could you please provide the specific train/valid/test data IDs for the methylation_data.pkl file? This information would be of great value for my project and help ensure that I am using the data correctly.

Additionally, I would like to mention that it is challenging to split the dataset based solely on the 142 dataset names and splitting methods provided in the supplementary materials. It would be much appreciated if you could offer some guidance or clarification on how to accurately map and divide the IDs in methylation_data.pkl.

![image](https://github.com/user-attachments/assets/2eabbfa6-bf85-4521-af61-191b7510e856)

**Comment by lucascamillomd** [comment]
Hi! Thanks for your question. I've added a folder with the individual pickled dataset files for both the train and test splits to [the Google Drive](https://drive.google.com/drive/u/2/folders/1THmHwEpO4CwjNsJ-C1pXxPRghV8tU09a). Hopefully that helps!

**Comment by ZwormZ** [comment]
Thank you very much for your prompt response and for providing the individual pickled dataset files for both the train and test splits in the Google Drive. I truly appreciate your help!

Upon examining the provided splits, I noticed that there are 8724 samples in the train split and 5944 samples in the test split. However, in the paper, it is mentioned that there are 8050 samples for training and validation, and 5455 samples for testing. I am curious about this discrepancy in the number of samples between the provided splits and the numbers stated in the paper. Is there any additional preprocessing or filtering that needs to be applied to the splits to obtain the exact numbers mentioned in the paper?

Thanks again!

**Comment by ZwormZ** [comment]
Hi, I was examining the data and came across some intriguing aspects concerning the age labels. Specifically, I observed that in the train split, the sample with the name GSE59157 has a maximum age of 144, while the sample with the name GSM1059477 has a minimum age of -0.65. Additionally, there are 228 samples with age values less than 0. These values seem to be outside the typical age range. Could you please share your thoughts on this matter and clarify if these values are expected or if they might be errors in the dataset?

Thank you for your time and assistance！

![image](https://github.com/user-attachments/assets/72e700d4-df93-4801-b9f9-e0046be96fe5)

![image](https://github.com/user-attachments/assets/04bbeb36-0e00-4277-a3a1-f24668b7c4d9)

**Comment by lucascamillomd** [comment]
You are right! The data I uploaded is before any filtering and QC. Brown unfortunately decreased the storage in my Google Drive a few months ago so I had to delete several of the processed files and was only able to keep a subset. 

I would just try to match the indices in the main dataset (the screenshot from your first comment) to the data in the folders data_test and data_train and check if that makes sense.

The 144 yo sample is definitely not real (and was filtered or relabelled). However, there should be several samples with a negative age. Any placental sample that was collected before 40 weeks of gestation (defined as 0) was encoded with a negative value.

Hope that helps and please let know if you have other questions!
