### ISSUE TITLE
what is train_imp in AltumAge_code.ipynb? 

### ISSUE THREAD

**Issue by Yang2888** [rsinghlab/AltumAge#9]
Thank you for your great work! I'm trying to re-implement it with the notebook you have provided. However, when trying to train the model, I find that train_imp is not defined in the notebook, leading to errors...

**Comment by lucascamillomd** [comment]
Thanks for your inquiry! ```train_imp``` should simply be replaced with the dataframe ```train``` as the processed data should not have any missing values. Let me know if that works!

**Comment by Yang2888** [comment]
Oh thank you for the reply, I have replaced train_imp to train, and the next problem is this line:
 `my_cpgs = train_imp.columns[elastic_net_model.coef_ != 0]`,
since my system is win10, I cannot use the elastic_net_model. How can I get my_cpgs?

**Comment by lucascamillomd** [comment]
```my_cpgs``` are only used for the AltumAge model trained with the subset of features that was selected by ElasticNet, but the final AltumAge uses all ~20k features so hopeful that's not essential!

**Comment by Yang2888** [comment]
I see now, I can just ignore that part or run the code in remote server.
